# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            R
tagline:          'for cats'
description:      'R for cats'
url:              http://rforcats.net/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# paginate:         5

github:
  repo:           https://github.com/sckott/rforcats
